### ISSUE TITLE
Information - atom-autocomplete-php

### ISSUE THREAD

**Issue by ghost** [vinicarlos56/php-composer-autocompletion#1]
Hello

There is another atom package that also provides PHP autocompletion via composer [1]. You may have already noticed this and started this package anyway because of personal reasons, in that case you can just close or ignore this message; I just wanted to mention it in case you didn't see it yet, in the event that you might want to collaborate ;-).

[1] https://github.com/Peekmo/atom-autocomplete-php

**Comment by vinicarlos56** [comment]
Hi

Yes, I've seen that already, but I was trying to learn how to create an atom package, so the best way to achieve that is to create one.

The solution I came up with is simpler and more straight forward than yours, although yours is more complete, I thought on try to contribute but at first it seemed too complicated because I was not used to the editor's approach.

My plans to this package is to support the most used scenarios only and give support on that, and seems that the other package is trying to come up with a more complete solution.

I might help as well, but I would just need some introduction first and we can share ideas.

Thanks for getting in touch and sorry for the delayed response!

Cheers
